// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdhlfgyfbiglybzcbzpa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkaGxmZ3lmYmlnbHliemNienBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMzMzODQsImV4cCI6MjA1NzkwOTM4NH0.vAulof-9NE6d9jcKmgdGO5Ytr_-JHwmAygdOavV3XbQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});